name: tests-shards.yml

# виконується при таких подіях:
on:
  # додавання змін у гілку main
  push:
    branches: [ main ]
  # запит на додавання змін у гілку main
  pull_request:
    branches: [ main ]

# перелік робіт
jobs:
  # назва роботи
  tests-shards:
    # Використовується хмарне середовище GitHub з останнім образом Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4]
    steps:
      # Клонування репозиторію у середовище
      - uses: actions/checkout@v5
      # Встановлення Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      # Запуск тестів
      - name: Run tests shards
        run: yarn jest --shard=${{matrix.shard}}/4 --maxWorkers=4
